# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a8c37fc4adb3eefa75e3f76c038174ae8f4d1b14c6df9885f14e97abbd87943e918b8ec4864bf71556fe4ada1d59b5235125ba65b94e332461454ee287ccb8

test:
  secret_key_base: f6365caa07985e363b987af5d7b24e24c00f92a7597e7e304950db5bb674ea0d8b75cb30e4cecc80deee59fac197197d8b0b9e33f46a97d78b3f95043d07169a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
